[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = "Testing"
authors = ["cosmin <cosminpetcu@live.com>"]

[tool.poetry.dependencies]
python = "^3.6.5"
pendulum = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
